INSERT INTO States (StateName,Country,Abbreviation) VALUES
  ("ALABAMA","USA","AL"),
  ("ALASKA","USA","AK"),
  ("AMERICAN SAMOA","USA","AS"),
  ("ARIZONA","USA","AZ"),
  ("ARKANSAS","USA","AR"),
  ("CALIFORNIA","USA","CA"),
  ("COLORADO","USA","CO"),
  ("CONNECTICUT","USA","CT"),
  ("DELAWARE","USA","DE"),
  ("DISTRICT OF COLUMBIA","USA","DC"),
  ("FEDERATED STATES OF MICRONESIA","USA","FM"),
  ("FLORIDA","USA","FL"),
  ("GEORGIA","USA","GA"),
  ("GUAM","USA","GU"),
  ("HAWAII","USA","HI"),
  ("IDAHO","USA","ID"),
  ("ILLINOIS","USA","IL"),
  ("INDIANA","USA","IN"),
  ("IOWA","USA","IA"),
  ("KANSAS","USA","KS"),
  ("KENTUCKY","USA","KY"),
  ("LOUISIANA","USA","LA"),
  ("MAINE","USA","ME"),
  ("MARSHALL ISLANDS","USA","MH"),
  ("MARYLAND","USA","MD"),
  ("MASSACHUSETTS","USA","MA"),
  ("MICHIGAN","USA","MI"),
  ("MINNESOTA","USA","MN"),
  ("MISSISSIPPI","USA","MS"),
  ("MISSOURI","USA","MO"),
  ("MONTANA","USA","MT"),
  ("NEBRASKA","USA","NE"),
  ("NEVADA","USA","NV"),
  ("NEW HAMPSHIRE","USA","NH"),
  ("NEW JERSEY","USA","NJ"),
  ("NEW MEXICO","USA","NM"),
  ("NEW YORK","USA","NY"),
  ("NORTH CAROLINA","USA","NC"),
  ("NORTH DAKOTA","USA","ND"),
  ("NORTHERN MARIANA ISLANDS","USA","MP"),
  ("OHIO","USA","OH"),
  ("OKLAHOMA","USA","OK"),
  ("OREGON","USA","OR"),
  ("PALAU","USA","PW"),
  ("PENNSYLVANIA","USA","PA"),
  ("PUERTO RICO","USA","PR"),
  ("RHODE ISLAND","USA","RI"),
  ("SOUTH CAROLINA","USA","SC"),
  ("SOUTH DAKOTA","USA","SD"),
  ("TENNESSEE","USA","TN"),
  ("TEXAS","USA","TX"),
  ("UTAH","USA","UT"),
  ("VERMONT","USA","VT"),
  ("VIRGIN ISLANDS","USA","VI"),
  ("VIRGINIA","USA","VA"),
  ("WASHINGTON","USA","WA"),
  ("WEST VIRGINIA","USA","WV"),
  ("WISCONSIN","USA","WI"),
  ("WYOMING","USA","WY"),
  ("ARMED FORCES AMERICAS (EXCEPT CANADA)","USA","AA"),
  ("ARMED FORCES AFRICA, CANADA, EUROPE, OR MIDDLE EAST","USA","AE"),
  ("ARMED FORCES PACIFIC","USA","AP"),
  ("ALBERTA","Canada","AB"),
  ("BRITISH COLUMBIA","Canada","BC"),
  ("MANITOBA","Canada","MB"),
  ("NEW BRUNSWICK","Canada","NB"),
  ("NEWFOUNDLAND & LABRADOR","Canada","NL"),
  ("NORTHWEST TERRITORIES","Canada","NT"),
  ("NOVA SCOTIA","Canada","NS"),
  ("NUNAVUT","Canada","NU"),
  ("ONTARIO","Canada","ON"),
  ("PRINCE EDWARD ISLAND","Canada","PE"),
  ("QUEBEC","Canada","QC"),
  ("SASKATCHEWAN","Canada","SK"),
  ("YUKON","Canada","YT")
;